{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabora.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    confighash: config-{{ .Values.collabora | toYaml | sha256sum | trunc 32 }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: collabora
data:
  {{- if .Values.collabora.extra_params }}
  extra_params: {{ .Values.collabora.extra_params }}
  {{- end }}
  {{- if .Values.collabora.server_name }}
  server_name: {{ .Values.collabora.server_name }}
  {{- end }}
  {{- range $k,$v := .Values.collabora.aliasgroups }}
  {{- $alias := $v.host }}
  {{- if $v.aliases }}
    {{- $alias := printf "%s,%s" $alias (join "," $v.aliases) }}
  aliasgroup{{ add $k 1 }}: {{ $alias }}
  {{- else }}
  aliasgroup{{ add $k 1 }}: {{ $alias }}
  {{- end }}
  {{- end }}
  {{- if .Values.collabora.coolkitconfig_xcu_content }}
  coolkitconfig.xcu: |
    {{ .Values.collabora.coolkitconfig_xcu_content | nindent 4 }}
  {{- end }}
  {{- if .Values.collabora.coolwsd_xml_content }}
  coolwsd.xml: |
    {{ .Values.collabora.coolwsd_xml_content | nindent 4 }}
  {{- end }}
