apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-updater-binding
subjects:
- kind: ServiceAccount
  name: {{ include "livekit-server.serviceAccountName" . }}
roleRef:
  kind: Role
  name: deployment-updater-role
  apiGroup: rbac.authorization.k8s.io
