apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-updater-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
