apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.livekit.prometheus_port }}
    - port: {{ .Values.livekit.prometheus_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
