#
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: %%CHOOSE_ONE_FROM_CHART_CATEGORIES_FILE%%
  licenses: Apache-2.0
apiVersion: v2
appVersion: %%UPSTREAM_PROJECT_VERSION%%
dependencies:
  - name: common
    repository: "file://../../../common/charts/common"
    version: 2.31.1
description: %%DESCRIPTION%%
home: https://minbzk.github.io/mijn-bureau-infra/
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/%%IMAGE_NAME%%/img/%%IMAGE_NAME%%-stack-220x234.png
keywords:
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - %%UPSTREAM_PROJECT_KEYWORD%%
  - ...
maintainers:
  - name: mijn-bureau-infra
    url: "https://minbzk.github.io/mijn-bureau/"
name: %%CHART_NAME%%
sources:
  - %%UPSTREAM_PROJECT_SOURCE_CODE_URL%%
  - ...
version: 0.1.0
